### PR TITLE
fix: prevent deletion of protected keys

### LINKED ISSUE #1325: Enhance DeleteVerbHandler so it prevents deletion of important data
### Describe the bug

It is currently possible for an authenticate client to delete data such as the server's signing keypair

### Steps to reproduce
See https://github.com/atsign-foundation/operations/issues/14

### Expected behavior

DeleteVerbHandler should prevent deletion of data which is important to correct functioning. In addition to the signing keypair mentioned above, we should consider whether other data should be deletable (e.g. `public:publickey@<atSign>`)

### PR DESCRIPTION
**Pull request by srieteja**
closes https://github.com/atsign-foundation/at_server/issues/1325

**- What I did**
- Improve the Delete verb to prevent the deletion of protected keys

**- How I did it**
- feat: introduce a new field in config.yaml for protectedKeys, for users to add protected keys
- feat: introduce new class variable 'protectedKeys' in AtSecondaryConfig that consists of ['signing_publickey', 'signing_privatekey', 'publickey', 'at_pkam_publickey']
- feat: introduce methods in DeleteVerbHandler that check if the key to be deleted is present in the list of protected keys, and returns an error message when true.
Note: The list of protected keys in config.yaml overrides the list of protectedKeys in AtSecondaryConfig

**- How to verify it**
- unit and functional tests added

**- Description for the changelog**

fix: prevent deletion of protected keys

### CODE REVIEW

File: packages/at_secondary_server/lib/src/verb/handler/delete_verb_handler.dart [hunk 1]
```diff
@@ -140,4 +149,23 @@ class DeleteVerbHandler extends ChangeVerbHandler {
...
+    for (var key in AtSecondaryConfig.protectedKeys) {
+      // convert generic key name to actual public key
+      // of format: key:@atsign
+      protectedKeys.add('$key$atsign');
+    }
+    return protectedKeys;
+  }
+
+  bool _isProtectedKey(String key) {
+    if (protectedKeys!.contains(key)) {
```
Comment (murali-shris) [inline packages/at_secondary_server/lib/src/verb/handler/delete_verb_handler.dart:164]: instead of contains..match the keys with the exact pattern
```
* public:signing_publickey<atsign>
* <atsign>:signing_privatekey<atsign>
* publickey<atsign>
* privatekey:at_pkam_publickey
```

**Review by murali-shris — CHANGES_REQUESTED** [review]

File: packages/at_secondary_server/lib/src/verb/handler/delete_verb_handler.dart (hunk 1 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/verb/handler/delete_verb_handler.dart:164]: since this is a list, contains would match the entire key with protectedKeys

File: packages/at_secondary_server/lib/src/server/at_secondary_config.dart [hunk 2]
```diff
@@ -675,6 +688,19 @@ class AtSecondaryConfig {
...
   }
 
+  static List<String> get protectedKeys {
+    try {
+      YamlList keys = getConfigFromYaml(['hive', 'protectedKeys']);
+      List<String> protectedKeys = [];
+      for (var key in keys) {
+        protectedKeys.add(key);
+      }
+      return protectedKeys.isEmpty ? _protectedKeys : protectedKeys;
```
Comment (murali-shris) [inline packages/at_secondary_server/lib/src/server/at_secondary_config.dart]: change this to
 protectedKeysFromConfig.isNotEmpty ? protectedKeysFromConfig : _defaultProtectedKeys;

**Review by murali-shris — DISMISSED** [review]
gave a review comment

File: packages/at_secondary_server/lib/src/server/at_secondary_config.dart (hunk 2 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/server/at_secondary_config.dart]: fixed as part of [567351b](https://github.com/atsign-foundation/at_server/pull/1471/commits/567351b6fe6c7c9af33b2644d579f4a616e8d71e)

File: packages/at_secondary_server/lib/src/server/at_secondary_config.dart [hunk 3]
```diff
@@ -675,6 +688,21 @@ class AtSecondaryConfig {
...
+        protectedKeysFromConfig.add(key);
+      }
+      return protectedKeysFromConfig.isNotEmpty
+          ? protectedKeysFromConfig
+          : _protectedKeys;
+    } on Exception {
+      return _protectedKeys;
+    }
+  }
+
```
Comment (gkc) [inline packages/at_secondary_server/lib/src/server/at_secondary_config.dart:709]: 1. The YAML config, if any, should _add_ to the default list of protected keys, not override it. The four keys named in `_protectedKeys` should _always_ be protected from deletion, regardless of what is in the YAML

2. Please use Sets instead of Lists. i.e. change the `_protectedKeys` to being a Set<String>, and change the return value of `get protectedKeys` to be a Set<String> and make the appropriate changes that flow from that

File: packages/at_secondary_server/config/config.yaml [hunk 4]
```diff
@@ -42,6 +40,10 @@ hive:
   # This is set to true by default. To retain the malformed keys on server start-up,
   # set the flag to false.
   shouldRemoveMalformedKeys: true
+  # List of keys are crucial for the server to function as expected
+  # The following keys cannot be deleted
+  # The list provided here will override the list of server's protected keys
```
Comment (gkc) [inline packages/at_secondary_server/config/config.yaml]: Should not override the default list; should augment it

File: packages/at_secondary_server/config/config.yaml [hunk 5]
```diff
@@ -42,6 +40,10 @@ hive:
...
+  protectedKeys: []
```
Comment (gkc) [inline packages/at_secondary_server/config/config.yaml:45]: If this were committed then, as currently implemented in AtSecondaryConfig, this empty list would override the default list of protected keys and thus they would be deletable

File: packages/at_secondary_server/lib/src/server/at_secondary_config.dart [hunk 6]
```diff
@@ -675,6 +688,21 @@ class AtSecondaryConfig {
     }
   }
 
+  static List<String> get protectedKeys {
+    try {
+      YamlList keys = getConfigFromYaml(['hive', 'protectedKeys']);
```
Comment (gkc) [inline packages/at_secondary_server/lib/src/server/at_secondary_config.dart:698]: I'd like to see unit tests with various flavours of yaml config to verify the logic

One way of enabling those tests to be written would be to augment AtSecondaryConfig to have a way to inject some yaml and change its `getConfigFromYaml` to use that yaml if it is set

**Review by gkc — CHANGES_REQUESTED** [review]

File: packages/at_secondary_server/config/config.yaml (hunk 5 above)
Comment (gkc) [reply packages/at_secondary_server/config/config.yaml:45]: Please also add to the comment in the yaml file to explain the `<@atSign>` formatting

File: packages/at_secondary_server/lib/src/server/at_secondary_config.dart (hunk 3 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/server/at_secondary_config.dart:709]: Change made as part of [d2b6e9d](https://github.com/atsign-foundation/at_server/pull/1471/commits/d2b6e9dd55f062903c77f60dde72db11c9b63d95)

File: packages/at_secondary_server/config/config.yaml (hunk 5 above)
Comment (srieteja) [reply packages/at_secondary_server/config/config.yaml:45]: change has been made as part of [99483ce](https://github.com/atsign-foundation/at_server/pull/1471/commits/99483cee49c36e172a76bcbd9f86841d976c5fbc)

File: packages/at_secondary_server/lib/src/server/at_secondary_config.dart (hunk 6 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/server/at_secondary_config.dart:698]: Changes to allow config injection into AtSecondaryConfig and the test itself are in [8ee7c62](https://github.com/atsign-foundation/at_server/pull/1471/commits/8ee7c6296c3707f9eeb1049140f66fa17e16d5dd). And the test config files and config util are part of [77c7be0](https://github.com/atsign-foundation/at_server/pull/1471/commits/77c7be013c407951bfe78a46650476131561b20d). What do you think about this approach @gkc

Comment (gkc) [reply packages/at_secondary_server/lib/src/server/at_secondary_config.dart:698]: Very good, thank you @srieteja

File: packages/at_secondary_server/test/delete_verb_test.dart [hunk 7]
```diff
@@ -96,4 +104,50 @@ void main() {
...
+    test('verify deletion of encryption public key', () {
+      var command = 'delete:$AT_ENCRYPTION_PUBLIC_KEY@alice';
+      var paramsMap = getVerbParam(Delete().syntax(), command);
+      expect(
+          () =>
+              handler.processVerb(Response(), paramsMap, mockInboundConnection),
+          throwsA(
+              predicate((exception) => exception is UnAuthorizedException)));
+    });
+
```
Comment (gkc) [inline packages/at_secondary_server/test/delete_verb_test.dart:143]: You need to add one more test asserting that the pkam public key may not be deleted

File: packages/at_secondary_server/test/delete_verb_test.dart [hunk 8]
```diff
@@ -96,4 +104,50 @@ void main() {
...
+    test(
+        'Verify protectedKeys from configYaml being appended to the list of protectedKeys in AtSecondaryConfig',
+        () {
+          TestConfigUtil.setTestConfig(1);
+          expect(AtSecondaryConfig.protectedKeys.length, 7);
+          TestConfigUtil.setTestConfig(2);
+          expect(AtSecondaryConfig.protectedKeys.length, 6);
+          TestConfigUtil.resetTestConfig();
+        });
+  });
```
Comment (gkc) [inline packages/at_secondary_server/test/delete_verb_test.dart:191]: 1. Please add a test_config_3.yaml which has `protectedKeys: []` and an expect for the resultant `AtSecondaryConfig.protectedKeys.length`
2. For each testConfig 1, 2 and 3, add an expect that `AtSecondaryConfig.protectedKeys` contains the core set of four that should always be present

File: tests/at_functional_test/test/delete_verb_test.dart [hunk 9]
```diff
@@ -152,6 +153,35 @@ void main() {
...
+  test('delete verb for an protected key - pkam_publickey', () async {
+    ///DELETE VERB
+    await socket_writer(
+        socketFirstAtsign!, 'delete:privatekey:at_pkam_publickey');
+    var response = await read();
+    print('delete verb response : $response');
+    // the error is an expected behaviour
+    assert((response.contains('Invalid syntax')));
+  });
+
```
Comment (gkc) [inline tests/at_functional_test/test/delete_verb_test.dart:220]: Please add explicit tests for the other two core protected keys (public encryption key, signing private key)

**Review by gkc — CHANGES_REQUESTED** [review]

File: packages/at_secondary_server/test/delete_verb_test.dart (hunk 7 above)
Comment (srieteja) [reply packages/at_secondary_server/test/delete_verb_test.dart:143]: This has been added as part of 73086dfc94ab73767bd16b3968ade74f3da04b0c

File: packages/at_secondary_server/test/delete_verb_test.dart (hunk 8 above)
Comment (srieteja) [reply packages/at_secondary_server/test/delete_verb_test.dart:191]: This has been added as part of 73086dfc94ab73767bd16b3968ade74f3da04b0c

File: tests/at_functional_test/test/delete_verb_test.dart (hunk 9 above)
Comment (srieteja) [reply tests/at_functional_test/test/delete_verb_test.dart:220]: These tests have been added through 6fcdede737deb85ee00f32961f10fffa2d0c9b1a

**Comment by gkc** [comment]
@srieteja is this ready for review again?

**Comment by srieteja** [comment]
> @srieteja is this ready for review again?

Yes. All the requested changes have been made.

**Review by gkc — APPROVED** [review]
LGTM! Thanks @srieteja
