### PR TITLE
fix: separate error codes when a pkam request is made through pending/denied apkam enrollment id

### LINKED ISSUE #99: pkam enrollment error code difference when enrollment is pending/denied
### Describe the bug

When enrollment is in pending/denied state, we get the same error code from server
E.g
error:AT0401-Exception: enrollment id: 8d2b8340-c47b-4886-828e-ac6b14e8165b is not approved 

Add a different error code which will help to differentiate error for pending vs denied enrollment

### Steps to reproduce

1. Client which is in already enrolled state must be running. 
e.g https://gist.github.com/murali-shris/55d1d67a4510bed1363d811140592444
2. Send a enroll request to server
3. Running client denies the enrollment or takes no action
4. Observe the error code when enrollment is i) pending ii)denied

### Expected behavior

* different error code/message for enrollment pending vs denied
* introduce new error code series for enrollment related exceptions thrown from server

### PR DESCRIPTION
**Pull request by srieteja**
closes https://github.com/atsign-foundation/at_protocol/issues/99
**- What I did**
- Separate error codes when a pkam request is fails for pending/denied apkam enrollment id
- PkamVerbHandler refactoring
- fix: base_response_handler does not return errors

**- How I did it**
- Introduced new error codes in at_commons which are now consumed and thrown from PkamVerbHandler

**- How to verify it**
- unit tests present in pkam_verb_test

**- Description for the changelog**

- fix: separate error codes when a pkam request fails for pending/denied apkam enrollment id
- fix: modified base_response_handler behaviour to return errorCode and errorMessage when Response.isError is set to true

### CODE REVIEW

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart [hunk 1]
```diff
@@ -45,31 +46,19 @@ class PkamVerbHandler extends AbstractVerbHandler {
...
-          throw UnAuthenticatedException(response.errorMessage);
-        }
-      }
+      response = await handleEnrollment(key, enrollId, response);
+      // fetch publicKey from response
+      // _handleEnrollment store publicKey as response.data
+      publicKey = response.data;
+      pkamAuthType = AuthType.apkam;
+      // set response.data to success which will be sent as the verb response
+      response.data = 'success';
```
Comment (sitaram-kalluri) [inline packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: At this point, the authentication is not completed. Only APKAM public key is fetched. So, suggest to avoid setting response.data to "success".
Also, suggest to rename "handleEnrollment" as "fetchAPKAMPublicKey" to clearly describe the method purpose.

**Review by sitaram-kalluri — CHANGES_REQUESTED** [review]

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart (hunk 1 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: These changes have been made in [d6c8d9b](https://github.com/atsign-foundation/at_server/pull/1520/commits/d6c8d9b4373d495161dcb746ce1551715f1ca1d0)

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart [hunk 2]
```diff
@@ -144,4 +137,44 @@ class PkamVerbHandler extends AbstractVerbHandler {
       throw UnAuthenticatedException('pkam authentication failed');
     }
   }
+
+  @visibleForTesting
+  Future<Response> fetchApkamPublicKey(
+      String key, String enrollId, Response response) async {
+    var enrollData = await keyStore.get(key);
```
Comment (sitaram-kalluri) [inline packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: keystore.get(key) throws 'KeyNotFoundException' when an enrollment key does not exist. 
Please handle the case when an enrollment key does not exist in the keystore.

**Review by sitaram-kalluri — CHANGES_REQUESTED** [review]

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart [hunk 3]
```diff
@@ -82,14 +74,99 @@ class PkamVerbHandler extends AbstractVerbHandler {
...
+  /// Otherwise returns [Response] with appropriate [Response.errorCode] and [Response.errorMessage]
+  /// Throws [KeyNotFoundException] if the key for provided [enrollId] does not exist
+  @visibleForTesting
+  Future<dynamic> handleApkamVerification(
+      String enrollId, String atSign, Response response) async {
+    String enrollmentKey =
+        '$enrollId.$newEnrollmentKeyPattern.$enrollManageNamespace$atSign';
+    var enrollData = await keyStore.get(enrollmentKey);
+    final atData = enrollData.data;
+    logger.finer('handleApkamVerification() fetched enrollData: $atData');
```
Comment (sitaram-kalluri) [inline packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: Please remove this log statement. atData contains apkamPublicKey and other enrollment data which makes logs noisy

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart [hunk 4]
```diff
@@ -82,14 +74,99 @@ class PkamVerbHandler extends AbstractVerbHandler {
...
+    // This means that the enrollmentId provided is APPROVED
+    return enrollDataStoreValue.apkamPublicKey;
+  }
 
+  @visibleForTesting
+  Response verifyEnrollApproval(
+      String approvalState, String enrollId, Response response) {
+    // the following is a function that based on the EnrollStatus sets
+    // appropriate error codes and messages
+    Response getApprovalStatus(EnrollStatus enrollStatus) {
```
Comment (sitaram-kalluri) [inline packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: Suggest not to use nested methods.

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart [hunk 5]
```diff
@@ -82,14 +74,99 @@ class PkamVerbHandler extends AbstractVerbHandler {
...
+    }
+    // If response.isError is NOT true, return the public key to continue authentication
+    // using apkam public key
+    // This means that the enrollmentId provided is APPROVED
+    return enrollDataStoreValue.apkamPublicKey;
+  }
 
+  @visibleForTesting
+  Response verifyEnrollApproval(
+      String approvalState, String enrollId, Response response) {
```
Comment (murali-shris) [inline packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: don't pass an object and modify the state inside the method.
Construct a new response object inside the method and return.

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart [hunk 6]
```diff
@@ -82,14 +74,99 @@ class PkamVerbHandler extends AbstractVerbHandler {
...
 
-    //retrieve stored secret using sessionid and atsign
-    var storedSecret = await keyStore.get('private:$sessionID$atSign');
-    storedSecret = storedSecret?.data;
+  /// Performs operations required for apkam authentication
+  /// Returns pkamPublicKey if the [enrollId] is [EnrollStatus.approved]
+  /// Otherwise returns [Response] with appropriate [Response.errorCode] and [Response.errorMessage]
+  /// Throws [KeyNotFoundException] if the key for provided [enrollId] does not exist
+  @visibleForTesting
+  Future<dynamic> handleApkamVerification(
```
Comment (murali-shris) [inline packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: remove future dynamic and have an internal object.
Also remove response object from input param
e.g 
class ApkamVerificationResult {
Response response;
String apkamPublicKey;
}

**Comment by murali-shris** [comment]
Add inline comments only when there is necessity. do not add comments for self explanatory code.

**Comment by murali-shris** [comment]
check the functional test failure in at_server

**Review by murali-shris — CHANGES_REQUESTED** [review]

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart (hunk 2 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: This case will be handled by the GlobalExceptionHandler

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart [hunk 7]
```diff
@@ -38,58 +39,122 @@ class PkamVerbHandler extends AbstractVerbHandler {
...
-    var storedSecret = await keyStore.get('private:$sessionID$atSign');
-    storedSecret = storedSecret?.data;
+  @visibleForTesting
+  Future<ApkamVerificationResult> handleApkamVerification(
+      String enrollId, String atSign) async {
+    String enrollmentKey =
+        '$enrollId.$newEnrollmentKeyPattern.$enrollManageNamespace$atSign';
+    var enrollData = await keyStore.get(enrollmentKey);
+    final atData = enrollData.data;
+    logger.finer('fetched enrollData: $atData');
```
Comment (sitaram-kalluri) [inline packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: Please remove this log statement. Logging entire enrollment data which includes encrypted keys makes log noisy. Please remove any log statment's that contains the public/private key pair

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart [hunk 8]
```diff
@@ -38,58 +39,122 @@ class PkamVerbHandler extends AbstractVerbHandler {
...
+    apkamResult.publicKey = enrollDataStoreValue.apkamPublicKey;
+    return apkamResult;
+  }
 
+  @visibleForTesting
+  Response verifyEnrollApproval(String approvalState, String enrollId) {
+    Response response = Response();
+    // the following is a function that based on the EnrollStatus sets
+    // appropriate error codes and messages
+    void getApprovalStatus(EnrollStatus enrollStatus) {
```
Comment (sitaram-kalluri) [inline packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: Please do not have nested methods. Move getApprovalStatus outside verifyEnrollApproval method.

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart [hunk 9]
```diff
@@ -131,17 +195,11 @@ class PkamVerbHandler extends AbstractVerbHandler {
...
-      atConnectionMetadata.isAuthenticated = false;
-      response.data = 'failure';
-      logger.severe('pkam authentication failed');
-      throw UnAuthenticatedException('pkam authentication failed');
-    }
+    return isValidSignature;
   }
 }
+
+class ApkamVerificationResult {
```
Comment (sitaram-kalluri) [inline packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart:202]: This class creates a new Response object which is not necessary. You can use the response object in processVerb method to set the error code and description. 
The discussion yesterday was not to over load the response object to carry the APKAM public key. 
1. Remove this class.
2. Pass the response object in processVerb method only to set the error codes and description.
3. If the enrollment is approved, Use a local String variable to return the APKAM public key or just `return enrollDataStoreValue.apkamPublicKey`

**Review by sitaram-kalluri — CHANGES_REQUESTED** [review]

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart (hunk 6 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: changes made as part of [7566e7e](https://github.com/atsign-foundation/at_server/pull/1520/commits/7566e7e79435c00f0b11a050b6cbc72ebbf54487)

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart (hunk 5 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: changes made as part of [7566e7e](https://github.com/atsign-foundation/at_server/pull/1520/commits/7566e7e79435c00f0b11a050b6cbc72ebbf54487)

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart (hunk 8 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: addressed as part of [270b30a](https://github.com/atsign-foundation/at_server/pull/1520/commits/270b30a26cf30cd073e04d917877ec274009985e)

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart (hunk 7 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: addressed as part of [270b30a](https://github.com/atsign-foundation/at_server/pull/1520/commits/270b30a26cf30cd073e04d917877ec274009985e)

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart (hunk 4 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: addressed as part of [270b30a](https://github.com/atsign-foundation/at_server/pull/1520/commits/270b30a26cf30cd073e04d917877ec274009985e)

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart (hunk 3 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: addressed as part of [270b30a](https://github.com/atsign-foundation/at_server/pull/1520/commits/270b30a26cf30cd073e04d917877ec274009985e)

**Review by sitaram-kalluri — DISMISSED** [review]

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart [hunk 10]
```diff
@@ -38,58 +39,116 @@ class PkamVerbHandler extends AbstractVerbHandler {
...
+  }
 
+  Response _getApprovalStatus(
+      EnrollStatus enrollStatus, enrollId, approvalState) {
+    Response response = Response();
+    switch (enrollStatus) {
+      case EnrollStatus.denied:
+        response.isError = true;
+        response.errorCode = 'AT0025';
+        response.errorMessage = 'enrollment_id: $enrollId is not approved |'
```
Comment (murali-shris) [inline packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: enrollment_id: $enrollId is denied

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart [hunk 11]
```diff
@@ -38,58 +39,116 @@ class PkamVerbHandler extends AbstractVerbHandler {
...
+            ' Status: $approvalState';
+        break;
+      case EnrollStatus.pending:
+        response.isError = true;
+        response.errorCode = 'AT0026';
+        response.errorMessage = 'enrollment_id: $enrollId is not approved |'
```
Comment (murali-shris) [inline packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: enrollment_id: $enrollId is pending

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart [hunk 12]
```diff
@@ -38,58 +39,116 @@ class PkamVerbHandler extends AbstractVerbHandler {
...
+            ' Status: $approvalState';
+        break;
+      case EnrollStatus.approved:
+        // do nothing when enrollment is approved
+        break;
+      case EnrollStatus.revoked:
+        response.isError = true;
+        response.errorCode = 'AT0027';
+        response.errorMessage = 'enrollment_id: $enrollId is not approved |'
```
Comment (murali-shris) [inline packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: enrollment_id: $enrollId is revoked

**Review by murali-shris — CHANGES_REQUESTED** [review]

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart (hunk 12 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: resolved as part of [3ade88d](https://github.com/atsign-foundation/at_server/pull/1520/commits/3ade88d17d2705baac492c17299f4aef2713acd7)

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart (hunk 11 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: resolved as part of [3ade88d](https://github.com/atsign-foundation/at_server/pull/1520/commits/3ade88d17d2705baac492c17299f4aef2713acd7)

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart (hunk 10 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: resolved as part of [3ade88d](https://github.com/atsign-foundation/at_server/pull/1520/commits/3ade88d17d2705baac492c17299f4aef2713acd7)

**Review by murali-shris — DISMISSED** [review]

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart [hunk 13]
```diff
@@ -38,58 +39,113 @@ class PkamVerbHandler extends AbstractVerbHandler {
...
+    }
+    return response;
+  }
+
+  Future<bool> _validateSignature(
+      var verbParams, var sessionId, String atSign, String publicKey) async {
+    var signature = verbParams[AT_PKAM_SIGNATURE]!;
+    var signingAlgo = verbParams[AT_PKAM_SIGNING_ALGO];
+    var hashingAlgo = verbParams[AT_PKAM_HASHING_ALGO];
     var signingAlgoEnum;
```
Comment (gkc) [inline packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: Please follow dart style and make this `SigningAlgoType? signingAlgoEnum;`

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart [hunk 14]
```diff
@@ -38,58 +39,113 @@ class PkamVerbHandler extends AbstractVerbHandler {
...
     var inputSignature;
```
Comment (gkc) [inline packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: Please follow dart style and make this `Uint8List? inputSignature;`

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart [hunk 15]
```diff
@@ -116,10 +172,9 @@ class PkamVerbHandler extends AbstractVerbHandler {
     }
     logger.finer('hashingAlgoEnum: $hashingAlgoEnum');
```
Comment (gkc) [inline packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart:156]: Please follow dart style and change `var hashingAlgoEnum` above to `HashingAlgoType? hashingAlgoEnum;`

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart [hunk 16]
```diff
@@ -116,10 +172,9 @@ class PkamVerbHandler extends AbstractVerbHandler {
...
     final verificationInput = AtSigningVerificationInput(
-        utf8.encode('$sessionID$atSign:$storedSecret') as Uint8List,
+        utf8.encode('$sessionId$atSign:$storedSecret') as Uint8List,
         inputSignature,
         publicKey);
-    //
     verificationInput.signingAlgoType = signingAlgoEnum;
     verificationInput.hashingAlgoType = hashingAlgoEnum;
     verificationInput.signingMode = AtSigningMode.pkam;
```
Comment (gkc) [inline packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart:164]: Before doing the signature verification, please handle conditions where any of signingAlgoEnum, inputSignature or hashingAlgoEnum are null. You can then add `!` where signingAlgoEnum, hashingAlgoEnum and inputSignature are referenced

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart [hunk 17]
```diff
@@ -13,6 +13,7 @@ import 'package:at_server_spec/src/connection/at_connection.dart';
 import 'package:at_chops/at_chops.dart';
```
Comment (gkc) [inline packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart:12]: Remove unnecessary import of src from at_server_spec package on line 12

**Review by gkc — CHANGES_REQUESTED** [review]
Some changes for dart style and better null safety handling

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart (hunk 13 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: changed as part of [05f42a0](https://github.com/atsign-foundation/at_server/pull/1520/commits/05f42a080aa3b989ce7d6bddb7dbc3489b2825d5)

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart (hunk 14 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart]: changed as part of [05f42a0](https://github.com/atsign-foundation/at_server/pull/1520/commits/05f42a080aa3b989ce7d6bddb7dbc3489b2825d5)

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart (hunk 15 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart:156]: changed as part of [05f42a0](https://github.com/atsign-foundation/at_server/pull/1520/commits/05f42a080aa3b989ce7d6bddb7dbc3489b2825d5)

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart (hunk 16 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart:164]: changed as part of [05f42a0](https://github.com/atsign-foundation/at_server/pull/1520/commits/05f42a080aa3b989ce7d6bddb7dbc3489b2825d5). The new methods(_getSigningAlgoType() and _getHashingAlgoType()) ensure that the signingAlgoEnum and hashingAlgoEnum have default values, hence not nullable

File: packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart (hunk 17 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/verb/handler/pkam_verb_handler.dart:12]: changed as part of [05f42a0](https://github.com/atsign-foundation/at_server/pull/1520/commits/05f42a080aa3b989ce7d6bddb7dbc3489b2825d5)

File: packages/at_secondary_server/test/pkam_verb_test.dart [hunk 18]
```diff
@@ -16,52 +18,122 @@ void main() {
...
-    expect(verb is Pkam, true);
+    test('test pkam verb handler getVerb', () {
+      var verbHandler = PkamVerbHandler(keyStoreManager!.getKeyStore());
+      var verb = verbHandler.getVerb();
+      expect(verb is Pkam, true);
+    });
+
+    test('test pkam verb - upper case with spaces', () {
+      var command = 'PK AM:';
+      command = SecondaryUtil.convertCommand(command);
```
Comment (gkc) [inline packages/at_secondary_server/test/pkam_verb_test.dart:62]: @murali-shris Why does `convertCommand` replace spaces?

**Review by gkc — APPROVED** [review]
One more question for @murali-shris which is not about this PR specifically, so this PR is good to go

File: packages/at_secondary_server/test/pkam_verb_test.dart (hunk 18 above)
Comment (murali-shris) [reply packages/at_secondary_server/test/pkam_verb_test.dart:62]: I guess to handle spaces in between verb name accidentally added by clients
