### PR TITLE
fix: Refactor getEntries method to improve time and space complexity

### LINKED ISSUE #1469: Refactor the commit log keystore to improve time and space complexity
- On the server start-up the commit log key-store causes the initial memory spike which cause the server to crash due to out of memory exception.
- The initial sync and the delta causes the memory spike.

Refactoring the commit log key-store as follows to address the time and space complexity issue:

Refactor "_getCommitIdMap" and "_updateCacheLog" method to sort the entries in ascending order by commit-ids.
To maintain the entries in sorted order, if a key exists in the map, remove the entry and add the key again to ensure the key is added to end of the map.
Refactor "getEntries" method
The "getEntries" at the moment loads all the keys from the commit log keystore into the memory. However, the server only returns 25 keys or untill the buffer is full (which ever happens first). So loading all the keys each time to consumes a lot of memory and time as well.
Refactored the method to load only specific number of keys. Added an optional field "limit" to configure how many keys to load into the memory for a batch. The "limit" is defaulted to 25.

### PR DESCRIPTION
**Pull request by sitaram-kalluri**
**- What I did**
- Refactor methods in commit_log_keystore.dart to improve time and space complexity.

**- How I did it**
- Refactor "_getCommitIdMap" and "_updateCacheLog" method to sort the entries in ascending order by commit-ids.
   - To maintain the entries in sorted order, if a key exists in the map, remove the entry and add the key again to ensure the key is added to end of the map. 
- Refactor "getEntries" method 
  - The "getEntries" at the moment loads all the keys from the commit log keystore into the memory. However, the server only returns 25 keys or untill the buffer is full (which ever happens first). So loading all the keys each time to consumes a lot of memory and time as well.
  - Refactored the method to load only specific number of keys. Added an optional field "limit" to configure how many keys to load into the memory for a batch. The "limit" is defaulted to 25.

Pending Work:
- [x] Add unit tests
- [x] Improve dart docs and code comments

### CODE REVIEW

File: packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart [hunk 1]
```diff
@@ -165,12 +166,10 @@ class CommitLogKeyStore
           'Returning the lastSyncedEntry matching regex $regex from cache. lastSyncedKey : ${lastSyncedEntry!.atKey} with commitId ${lastSyncedEntry.commitId}');
       return lastSyncedEntry;
     }
```
Comment (gkc) [inline packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart:168]: If there is no entry in _lastSyncedEntryCacheMap, can we just return null rather than iterate through the full commit log? I know this is client-side code so not something to address in this PR but something to follow up on please @sitaram-kalluri (maybe create another ticket for this)

File: packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart [hunk 2]
```diff
@@ -289,14 +288,13 @@ class CommitLogKeyStore
...
   Future<List<CommitEntry>> getChanges(int sequenceNumber,
       {String? regex, int? limit}) async {
-    var changes = <CommitEntry>[];
-    var regexString = (regex != null) ? regex : '';
-    var values = await _getValues();
     try {
-      var keys = _getBox().keys;
-      if (keys.isEmpty) {
-        return changes;
+      if (_getBox().keys.isEmpty) {
```
Comment (gkc) [inline packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart]: use `_getBox().isEmpty` instead

File: packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart [hunk 3]
```diff
@@ -340,17 +338,29 @@ class CommitLogKeyStore
...
+      //  {k1, v1},
+      //  {k2, v2},
+      //  {k3, v3}
+      // }
+      // such that v1 < v2 < v3
+      //
+      // If a key exist in the _commitLogCacheMap, updating the commit entry will
+      // overwrite the existing key resulting into an unsorted map.
+      // Hence remove the key and insert at the last ensure the entry with highest commitEntry
+      // is always at the end of the map.
```
Comment (gkc) [inline packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart:360]: Thanks for the comment explaining the reasoning here! Will help future maintainers.

File: packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart [hunk 4]
```diff
@@ -364,6 +374,20 @@ class CommitLogKeyStore
...
+    //  {k2, v2},
+    //  {k3, v3}
+    // }
+    // such that v1 < v2 < v3
+    //
+    // If a key exist in the _commitLogCacheMap, updating the commit entry will
+    // overwrite the existing key resulting into an unsorted map.
+    // Hence remove the key and insert at the last ensure the entry with highest commitEntry
+    // is always at the end of the map.
+    _commitLogCacheMap.remove(key);
```
Comment (gkc) [inline packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart:390]: And again thanks for the explanatory comment

File: packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart [hunk 5]
```diff
@@ -376,25 +400,15 @@ class CommitLogKeyStore
...
-    return commitLogMap.values.toList();
+  Iterator<MapEntry<String, CommitEntry>> getEntries(int commitId,
+      {String regex = '.*', int limit = 25}) {
+    Iterable<MapEntry<String, CommitEntry>> commitEntriesIterable =
+        _commitLogCacheMap.entries
+            .where((element) =>
+                element.value.commitId! >= commitId &&
+                _acceptKey(element.value.atKey!, regex))
+            .take(limit);
+    return commitEntriesIterable.iterator;
```
Comment (gkc) [inline packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart:411]: Nicely done.

File: packages/at_persistence_secondary_server/test/commit_log_test.dart [hunk 6]
```diff
@@ -432,6 +432,71 @@ void main() async {
       }
     });
 
+    test(
+        'A test to verify entries in commit cache map are sorted by commit-id in descending order',
```
Comment (gkc) [inline packages/at_persistence_secondary_server/test/commit_log_test.dart]: ascending, not descending

File: packages/at_persistence_secondary_server/test/commit_log_test.dart [hunk 7]
```diff
@@ -432,6 +432,71 @@ void main() async {
...
+        }
+        if (itr.current.key == '@alice:key2.wavi@alice') {
+          expect(itr.current.value.commitId, 3);
+          expect(itr.current.value.operation, CommitOp.DELETE);
+        }
+        if (itr.current.key == '@alice:key1.wavi@alice') {
+          expect(itr.current.value.commitId, 4);
+          expect(itr.current.value.operation, CommitOp.UPDATE);
+        }
+      }
```
Comment (gkc) [inline packages/at_persistence_secondary_server/test/commit_log_test.dart]: I'd suggest removing the while and if statements with
```
      itr.moveNext();
      expect(itr.current.key, '@alice:key3.wavi@alice');
      expect(itr.current.value.commitId, 2);
      expect(itr.current.value.operation, CommitOp.UPDATE);

      itr.moveNext();
      expect(itr.current.key, '@alice:key2.wavi@alice');
      expect(itr.current.value.commitId, 3);
      expect(itr.current.value.operation, CommitOp.DELETE);

      itr.moveNext();
      expect(itr.current.key, '@alice:key1.wavi@alice');
      expect(itr.current.value.commitId, 4);
      expect(itr.current.value.operation, CommitOp.UPDATE);
```

**Review by gkc — CHANGES_REQUESTED** [review]
Excellent work. One change requested to part of a test; and an observation on a potential follow-up PR for performance gain on one of the client-only methods

File: packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart (hunk 2 above)
Comment (sitaram-kalluri) [reply packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart]: Updated the code.

File: packages/at_persistence_secondary_server/test/commit_log_test.dart (hunk 7 above)
Comment (sitaram-kalluri) [reply packages/at_persistence_secondary_server/test/commit_log_test.dart]: Updated the code as above.

File: packages/at_persistence_secondary_server/test/commit_log_test.dart (hunk 6 above)
Comment (sitaram-kalluri) [reply packages/at_persistence_secondary_server/test/commit_log_test.dart]: Done with the change.

File: packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart (hunk 1 above)
Comment (sitaram-kalluri) [reply packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart:168]: Sure Gary, Will create a ticket on this.

File: packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart (hunk 5 above)
Comment (sitaram-kalluri) [reply packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart:411]: Thank you Gary.

**Comment by sitaram-kalluri** [comment]
> Excellent work. One change requested to part of a test; and an observation on a potential follow-up PR for performance gain on one of the client-only methods

Thank you Gary.

**Review by gkc — APPROVED** [review]
