### PR TITLE
fix: introduce a new config key to store an atsign's blocklist

### LINKED ISSUE #1570: configKey is not well formed key
### Describe the bug

With the changes in the PR: https://github.com/atsign-foundation/at_server/pull/1569, three functional tests are failing with below exception

```
  From verb response data:_60f74087-c688-4c1b-805f-bcb5fe10f12f@alice🛠:eb1042bf-89a1-48c9-8750-130f025c66d7
  
  pkam verb response data:success
  
  FormatException: Unexpected character (at character 1)
  error:null:Exception: configkey is not well-formed key
```

When adding an atSign to the block list, the list of atSigns are stored aganist the key "configKey" which is not a well formed key. "configKey" does not adhere to the key format specified for AtKeys.

Referring to the changes APKAM changes, and the process of retrieving the highest commitId within the enrolled namespaces, we achieve this by extracting the namespace from the key using AtKey.fromString(key).namespace. However, when the key "configKey" is encountered, this action triggers the mentioned error within AtKey.fromString because "configKey" does not conform to the valid AtKey format.

### PR DESCRIPTION
**Pull request by srieteja**
Closes https://github.com/atsign-foundation/at_server/issues/1570 and https://github.com/atsign-foundation/at_server/issues/1204

**- What I did**
- introduce a new config key to store an at-sign's blocklist
- allow backward compatibility to ensure data stored under the old key is smoothly migrated to the new key
- ensure the new key is not synced to clients
- delete the old key after data migration, which is actually the cause of the issue linked above
- remove an unnecessary try-catch block in ConfigVerbHandler
- Replace assert statements in AtConfig with IllegalArgumentExceptions
- Group all the tests in at_persistence_secondary/at_config_test. Also added code to close the hive in the tearDown.

**- How I did it**
- New key that stores an at-sign's blocklist is: 'private:blocklist@atsign'.
- This key name is more descriptive of its function and ensures that this key is not synced to the client(Keys that start with 'private:' are not synced).
- When the new key is not found in the keystore, an attempt to fetch data with the old key is made. And then the existing data is stored with the new config-key while the old one is deleted.

**- How to verify it**
- added unit test to objectively verify backward compatibility
- existing unit and functional tests passing should indicate the proper working of this feature

**- Description for the changelog**

fix: introduce a new config key to store an at-sign's blocklist

### CODE REVIEW

File: packages/at_persistence_secondary_server/lib/src/config/at_config.dart [hunk 1]
```diff
@@ -154,13 +152,27 @@ class AtConfig {
...
       try {
-        existingData = await get(olConfigKey);
-        await (persistenceManager.getBox() as LazyBox).delete(olConfigKey);
+        existingData = await get(oldConfigKey);
+        AtData newAtData = AtData()..data = existingData?.data;
+        HiveKeyStoreHelper.getInstance().prepareDataForKeystoreOperation(
+            newAtData,
+            existingAtData: existingData);
+        // store the existing data with the new key
+        await (persistenceManager.getBox() as LazyBox).put(configKey, newAtData);
```
Comment (sitaram-kalluri) [inline packages/at_persistence_secondary_server/lib/src/config/at_config.dart]: Should we append atSign at the end of the config key to make a valid AtKey? For example `private:blocklist@alice`

**Review by sitaram-kalluri — CHANGES_REQUESTED** [review]

File: packages/at_persistence_secondary_server/lib/src/config/at_config.dart (hunk 1 above)
Comment (srieteja) [reply packages/at_persistence_secondary_server/lib/src/config/at_config.dart]: change has been made as part of [929408d](https://github.com/atsign-foundation/at_server/pull/1622/commits/929408d47379b1ac97dc317a40a834e7219e4cff)

**Review by murali-shris — APPROVED** [review]

**Review by sitaram-kalluri — APPROVED** [review]
