### PR TITLE
fix: Populate existing metadata for null values of new metadata

### LINKED ISSUE #1295: When updating metadata, it should be patched (merged), not overwritten
### Describe the bug

In #1287 we have a situation where
- an sshnpd program using newest version of dart client SDK was creating keys with a value in the new ivNonce metadata
- an older version of the sshnpd program was also creating (updating) those keys and, since it was unaware of new metadata, it did not send it in the batch update request to the server
- the server did not merge data appropriately

### Steps to reproduce

See #1287 

### Expected behavior

The Update and UpdateMeta verb handlers should
- retrieve the current AtMetadata, if any
- set values on it if and only if they have been sent by the client in the update command (i.e. they are present in the verb params)
- and that modified AtMetadata object is what should be saved back to the keystore

There is code in the persistence layer which has some intent along these lines; however - it is not possible to do this entirely in the persistence layer, as the persistence layer cannot know the difference between a field which was explicitly set to null by a client and sent as such in the update command, versus a field which was not sent by the client and thus has an implicit value of null

### Screenshots

_No response_

### Smartphones

_No response_

### Were you using an atApplication when the bug was found?

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sitaram-kalluri**
**- What I did**
* Ability to retain the existing metadata and reset the metadata. Following is expected behaviour.
  * If an attribute in AtMetadata is explicitly set to "null", then its value is reset. The attribute is set to null.
  * If an attribute in AtMetadata is not set, but has a value previously, then the previous value is fetched and updated.
  * If an attribute in AtMetadata is set with a new value, then the new value is set. Even if there, exists a previous value, it is overwritten.

**- How I did it**
* In AbstractUpdateVerbBuilder.dart, introduce a new method "_unsetOrRetainMetadata" which check if the metadata is null or "null" and performs the appropriate actions.
* Removed the UpdateParams from "UpdatePreProcessResult" class for the following reasons:
   * To my understanding, the UpdateParams is sent in the UpdatePreProcessResult to populate the optional named parameters of metadata in "put" method. The metadata in UpdateParams does not contain the above modifications (when metadata is null or "null""), and setting the optional parameters with metadata in UpdateParams will overwrite the changes made to AtMetadata.
   * The Metadata in UpdateParams is already available in AtData.AtMetadata and the logic to set the null or previous metadata is applied on AtData.AtMetadata. Hence, removed the UpdateParams from "UpdatePreProcessResult" and used atData.AtMetadata to populate the optional named parameters.
   
**- How to verify it**
* Updated the existing test case that covers the scenario.

* Tested on the server via OpenSSL terminal and below is the test log. (Repeated the below test scenarios after moving the logic to verb Handlers)

```
// Setting TTL value
@sitaram@update:ttl:1000000:@murali:key4@sitaram value4
data:25
@sitaram@llookup:all:@murali:key4@sitaram
data:{"key":"@murali:key4@sitaram","data":"value4","metaData":{"createdBy":"@sitaram","updatedBy":"@sitaram","createdAt":"2023-04-05 08:36:38.117Z","updatedAt":"2023-04-05 08:41:30.418Z","expiresAt":"2023-04-05 08:58:10.418Z","status":"active","version":4,"ttl":1000000}}
// Setting TTB value and TTL value is retained from the previous update
@sitaram@update:ttb:10:@murali:key4@sitaram value4
data:26
@sitaram@llookup:all:@murali:key4@sitaram
data:{"key":"@murali:key4@sitaram","data":"value4","metaData":{"createdBy":"@sitaram","updatedBy":"@sitaram","createdAt":"2023-04-05 08:36:38.117Z","updatedAt":"2023-04-05 08:41:52.863Z","availableAt":"2023-04-05 08:41:52.873Z","expiresAt":"2023-04-05 08:58:10.418Z","status":"active","version":5,"ttl":1000000,"ttb":10}}
// Setting dataSignature 
@sitaram@update:dataSignature:test:@murali:key4@sitaram value4
data:31
@sitaram@llookup:all:@murali:key4@sitaram
data:{"key":"@murali:key4@sitaram","data":"value4","metaData":{"createdBy":"@sitaram","updatedBy":"@sitaram","createdAt":"2023-04-05 08:36:38.117Z","updatedAt":"2023-04-05 08:44:19.826Z","availableAt":"2023-04-05 08:41:52.873Z","expiresAt":"2023-04-05 08:58:10.418Z","status":"active","version":10,"ttl":1000000,"ttb":10,"dataSignature":"test"}}
// Setting dataSignature to null to reset the metadata
@sitaram@update:dataSignature:null:@murali:key4@sitaram value4
data:32
@sitaram@llookup:all:@murali:key4@sitaram
data:{"key":"@murali:key4@sitaram","data":"value4","metaData":{"createdBy":"@sitaram","updatedBy":"@sitaram","createdAt":"2023-04-05 08:36:38.117Z","updatedAt":"2023-04-05 08:44:37.878Z","availableAt":"2023-04-05 08:41:52.873Z","expiresAt":"2023-04-05 08:58:10.418Z","status":"active","version":11,"ttl":1000000,"ttb":10}}
```

**- Description for the changelog**
* Modify the AtMetadataBuilder to preserve the existing metadata when not set. Reset the metadata when explicitly set to null.

### CODE REVIEW

File: packages/at_secondary_server/lib/src/verb/handler/abstract_update_verb_handler.dart [hunk 1]
```diff
@@ -197,12 +201,41 @@ abstract class AbstractUpdateVerbHandler extends ChangeVerbHandler {
     unawaited(notificationManager.notify(atNotification));
     return atNotification;
   }
+
+  /// If metadata contains "null" string, then reset the metadata. So set it to null
+  /// If metadata contains null (null object), then fetch the existing metadata.If
+  /// existing metadata value is not null, set it the current AtMetaData obj.
+  AtMetaData _setNullOrExistingMetadata(
```
Comment (murali-shris) [inline packages/at_secondary_server/lib/src/verb/handler/abstract_update_verb_handler.dart]: we can rename this to _unsetOrRetainMetadata

**Review by murali-shris — DISMISSED** [review]

File: packages/at_secondary_server/lib/src/verb/handler/abstract_update_verb_handler.dart (hunk 1 above)
Comment (sitaram-kalluri) [reply packages/at_secondary_server/lib/src/verb/handler/abstract_update_verb_handler.dart]: Sure Murali, Will rename the method

**Review by gkc — APPROVED** [review]
LGTM - thanks Sita
