### PR TITLE
fix: Hive max length bug

### LINKED ISSUE #1863: Inserting a 253-character key triggers server shutdown upon restart.
### Describe the bug

Restarting the server after inserting a key with 253 characters exits with the following error

SecondaryServerBootStrapper|Uncaught error: HiveError: Cannot read, unknown typeId: 241. Did you forget to register an adapter? 
 StackTrace: #0      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:325:11)
#1      CommitOpAdapter.read (package:at_persistence_secondary_server/src/log/commitlog/commit_entry.dart:99:71)
#2      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:328:33)
#3      BinaryReaderImpl.readEncrypted (package:hive/src/binary/binary_reader_impl.dart:342:24)
#4      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:278:26)
#5      StorageBackendVm.readValue.<anonymous closure> (package:hive/src/backend/vm/storage_backend_vm.dart:111:30)
<asynchronous suspension>
#6      _AsyncCompleter.complete (dart:async/future_impl.dart:41:3)
<asynchronous suspension>
#7      LazyBoxImpl.get (package:hive/src/box/lazy_box_impl.dart:32:19)

### Steps to reproduce

1. First Create a key with 253 characters - iujpsefqvdzmtqthrqbaxqszxokaiutvpnbcphcjvjghpdxzdwywfsaowruwafmcudeoarfhuncezjkwbdvprcbujeptisxkjtztxogqqrrnjpqrdsjmcrpmpusrkzaksdfleyzsuarjhsqvxwicxulzqjzcwwjaupxzoqfwenkfonwhxtmwamiyzqqoesnreknrzwxazvykbybafrlwgqsyreudprnakoioqiwoqiwqdebbdwbdywebwydbw
2. Then restart the server

### Expected behavior

Server should not exit

### Screenshots

Screenshot from 2024-03-26 16-42-08

### Smartphones

_No response_

### Were you using an atApplication when the bug was found?

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by murali-shris**
fixes: https://github.com/atsign-foundation/at_server/issues/1863
**- What I did**
- Fixed issue in persistence layer for keys with length greater than max length suppported in hive(currently 255)
**- How I did it**
- Added max length check in put, putAll and create methods in HiveKeyStoreImpl
- added unit tests
**- How to verify it**
- units tests should pass
- point to persistence branch and run at_client and server tests
https://github.com/atsign-foundation/at_client_sdk/pull/1281
https://github.com/atsign-foundation/at_server/pull/1877
-------------------------
With this fix, server will return data:null when updating key with length > 255 chars. Have to make fix in server to return correct error message.

### CODE REVIEW

**Review by gkc — CHANGES_REQUESTED** [review]
Should we restrict the length to 248 if it doesn't start with "cached:"? Leaves enough for a "cached:"prefix to be added on a caching atServer / client

**Comment by murali-shris** [comment]
> Should we restrict the length to 248 if it doesn't start with "cached:"? Leaves enough for a "cached:"prefix to be added on a caching atServer / client

sure Gary.

**Comment by murali-shris** [comment]
> > Should we restrict the length to 248 if it doesn't start with "cached:"? Leaves enough for a "cached:"prefix to be added on a caching atServer / client
> 
> sure Gary.

@gkc I had a discussion with @sitaram-kalluri on this. 
Let's say the key is @ bob: phone@ alice. This will be stored in alice's keystore. If the key has ttr, then @ bob will cache the key at his end. 255 char limit will be enforced at bob's keystore including cached:
In persistence layer, 255 can be the max limit
in client/server, 248 without cached: and 255 including cached:
is this fine?

**Comment by gkc** [comment]
> > > Should we restrict the length to 248 if it doesn't start with "cached:"? Leaves enough for a "cached:"prefix to be added on a caching atServer / client
> > 
> > 
> > sure Gary.
> 
> @gkc I had a discussion with @sitaram-kalluri on this. Let's say the key is @ bob: phone@ alice. This will be stored in alice's keystore. If the key has ttr, then @ bob will cache the key at his end. 255 char limit will be enforced at bob's keystore including cached: In persistence layer, 255 can be the max limit in client/server, 248 without cached: and 255 including cached: is this fine?

Yes I believe so

File: packages/at_persistence_secondary_server/test/at_notification_keystore_test.dart [hunk 1]
```diff
@@ -136,6 +136,22 @@ void main() async {
...
     });
+    test('test hive key exceeds max allowed chars', () async {
+      var keyStore = AtNotificationKeystore.getInstance();
+      var atNotification = (AtNotificationBuilder()
+            ..toAtSign = '@bob'
+            ..fromAtSign = '@alice'
+            ..id = '123')
+          .build();
+      var key =
+          'iujpsefqvdzmtqthrqbaxqszxokaiutvpnbcphcjvjghpdxzdwywfsaowruwafmcudeoarfhuncezjkwbdvprcbujeptisxkjtztxogqqrrnjpqrdsjmcrpmpusrkzaksdfleyzsuarjhsqvxwicxulzqjzcwwjaupxzoqfwenkfonwhxtmwamiyzqqoesnreknrzwxazvykbybafrlwgqsyreudprnakoioqiwoqiwqdebbdwbdywebwydbwrr@alice';
```
Comment (gkc) [inline packages/at_persistence_secondary_server/test/at_notification_keystore_test.dart]: For readability, instead of long string of letters unclear as to what length they are, can we instead create and use a function which returns a random string of whatever length is required

**Review by gkc — CHANGES_REQUESTED** [review]

File: packages/at_persistence_secondary_server/test/at_notification_keystore_test.dart (hunk 1 above)
Comment (murali-shris) [reply packages/at_persistence_secondary_server/test/at_notification_keystore_test.dart]: Done

**Review by gkc — APPROVED** [review]
