### PR TITLE
fix: improve logging and localized exception handling in pol_verb_handler and outbound_client

### LINKED ISSUE #1327: Improve null safety checks and exception handling around the pol auth flow
### Describe the bug

See incident report https://github.com/atsign-foundation/operations/issues/14

Incident took much longer than it should have to diagnose because of a lack of parameter value checks and more localized exception handling on both ends of the pol auth flow (OutboundClient, and PolVerbHandler) which in turn led to there being a severe lack of useful log messages to help diagnose the issue

### Expected behavior

Check variables for correctness of their values. (Non-null, in appropriate format, etc)
Do more localized exception handling so that, given an exception messages, it is easier to narrow down where the problem is occurring

### PR DESCRIPTION
**Pull request by srieteja**
closes https://github.com/atsign-foundation/at_server/issues/1327
**- What I did**
- Improve logger statements in outbound_client, pol_verb_handler which makes debugging easier
- Strict enforcement of datatypes for variables that are vital
- Localised exception handling, and rethrow to make it more easier to identify the error origin

**- How to verify it**
- More descriptive logger messages from outbound_client and pol_verb handler
- More accurate exception stacktraces

**- Description for the changelog**

fix: improve logging and localized exception handling in pol_verb_handler and outbound_client)

### CODE REVIEW

File: packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart [hunk 1]
```diff
@@ -301,16 +307,19 @@ class OutboundClient {
...
 
   void close() {
     if (outboundConnection != null) {
       outboundConnection!.close();
+      logger.finer('Outbound connection closed');
     }
   }
 
   bool isInValid() {
+    logger.finer('connection is invalid');
```
Comment (gkc) [inline packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart]: You are logging that the connection is invalid (a) with no additional context (which connection?) and (b) before you've actually checked if it is invalid

**Review by gkc — CHANGES_REQUESTED** [review]

File: packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart [hunk 2]
```diff
@@ -97,15 +98,18 @@ class OutboundClient {
       }
     } on SecondaryNotFoundException catch (e) {
       logger
-          .severe('secondary server not found for $toAtSign: ${e.toString()}');
+          .severe('Secondary server not found for $toAtSign\n${e.toString()}');
```
Comment (gkc) [inline packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart]: We should avoid breaking log messages over more than one line. Please revert to using colon `:` or pipe `|`

File: packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart [hunk 3]
```diff
@@ -224,6 +230,7 @@ class OutboundClient {
         return false;
       }
     } on ConnectionInvalidException {
+      logger.severe('Invalid connection: ${toString()}');
```
Comment (gkc) [inline packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart]: I guess you are intending this would be `${e.toString()}`? In which case you need to do `on ConnectionInvalidException catch (e) {`

File: packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart [hunk 4]
```diff
@@ -257,6 +264,7 @@ class OutboundClient {
       throw LookupException(
           'Exception writing to outbound socket ${e.toString()}');
     } on ConnectionInvalidException {
+      logger.severe('Invalid connection: ${toString()}');
```
Comment (gkc) [inline packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart]: See previous comment re line 233 above

File: packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart [hunk 5]
```diff
@@ -285,6 +293,7 @@ class OutboundClient {
...
```
Comment (gkc) [inline packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart]: See previous comment re line 233 above

File: packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart [hunk 6]
```diff
@@ -301,18 +310,30 @@ class OutboundClient {
...
+      logger.finer('Outbound connection closed');
     }
   }
 
   bool isInValid() {
-    return inboundConnection.isInValid() ||
-        (outboundConnection != null && outboundConnection!.isInValid());
+    bool isInvalid = false;
+    if (inboundConnection.isInValid()) {
+      logger.severe('Outbound Connection to $toAtSign is invalid');
```
Comment (gkc) [inline packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart]: This does not seem to warrant a SEVERE level of logging?

Also, the logged message is confusing - the message refers to 'Outbound Connection' but the check on the previous line is for inboundConnection

File: packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart [hunk 7]
```diff
@@ -301,18 +310,30 @@ class OutboundClient {
...
+      isInvalid = true;
+    }
+    if (outboundConnection != null && outboundConnection!.isInValid()) {
+      logger.severe(
+          'Inbound connection from ${inboundConnection.initiatedBy} is invalid');
```
Comment (gkc) [inline packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart]: This does not seem to warrant a SEVERE level of logging?

Also, the logged message is confusing - the message refers to 'Inbound connection' but the check on the previous line is on outboundConnection

File: packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart [hunk 8]
```diff
@@ -301,18 +310,30 @@ class OutboundClient {
...
+      isInvalid = true;
+    }
+    logger.severe('Invalid Connection: ${toString()}');
```
Comment (gkc) [inline packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart]: What are you intending to log here?

File: packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart [hunk 9]
```diff
@@ -360,6 +382,7 @@ class OutboundClient {
       throw LookupException(
           'Exception writing to outbound socket ${e.toString()}');
     } on ConnectionInvalidException {
+      logger.severe('Invalid connection: ${toString()}');
       throw OutBoundConnectionInvalidException('Outbound connection invalid');
```
Comment (gkc) [inline packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart:383]: Given you are re-throwing, a SEVERE level log message doesn't seem warranted

File: packages/at_secondary_server/lib/src/verb/handler/pol_verb_handler.dart [hunk 10]
```diff
@@ -107,12 +122,20 @@ class PolVerbHandler extends AbstractVerbHandler {
         } else {
           throw UnAuthenticatedException('Pol Authentication Failed');
         }
+      } else {
+        logger.finer('Outbound Client status: ${outBoundClient.toString()}');
+        logger.severe('fromPublicKey is $fromPublicKey\n'
+            'signedChallenge is $signedChallenge');
+        throw AtKeyNotFoundException(
```
Comment (gkc) [inline packages/at_secondary_server/lib/src/verb/handler/pol_verb_handler.dart]: Why AtKeyNotFoundException?

**Review by gkc — CHANGES_REQUESTED** [review]

File: packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart (hunk 8 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart]: I am trying to log the details of the Outbound client, hence calling the toString() in the same class. The idea is that OutboundClient.toString() displays the atsigns were dealing with and the status of the connection, handshake, etc.

File: packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart (hunk 3 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart]: My intention was to log the OutboundClient.toString(). In your opinion, do you think this provides any useful insight while debugging stuff ?

File: packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart (hunk 7 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart]: I have brought the logger level down as part of [3f36a53](https://github.com/atsign-foundation/at_server/pull/1367/commits/3f36a53d2a44ab80a2ce76e822e77844dba4d5b6). The mismatch of logger messages to inbound/outbound connection name has also been fixed

File: packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart (hunk 6 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart]: I have brought the logger level down as part of https://github.com/atsign-foundation/at_server/pull/1367/commits/f97e5e612ee1c2c211822c18c11f2c9398a226b7. The mismatch of logger messages to inbound/outbound connection name has been fixed in [3f36a53](https://github.com/atsign-foundation/at_server/pull/1367/commits/3f36a53d2a44ab80a2ce76e822e77844dba4d5b6)

File: packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart (hunk 2 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart]: reverted all the new-line related changes in [3f36a53](https://github.com/atsign-foundation/at_server/pull/1367/commits/3f36a53d2a44ab80a2ce76e822e77844dba4d5b6)

File: packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart (hunk 1 above)
Comment (srieteja) [reply packages/at_secondary_server/lib/src/connection/outbound/outbound_client.dart]: This has been fixed in [9ca8904](https://github.com/atsign-foundation/at_server/pull/1367/commits/9ca8904f127a7ca149124546cb54157003cdd939)

File: packages/at_secondary_server/lib/src/verb/handler/pol_verb_handler.dart (hunk 10 above)
Comment (purnimavenkatasubbu) [reply packages/at_secondary_server/lib/src/verb/handler/pol_verb_handler.dart]: Updated the exception

**Review by gkc — APPROVED** [review]
